language: python
python:
  - 3.5
  - 3.6
  - 3.7

services:
  - mongodb

before_script:
  - echo "replSet = rs0" | sudo tee -a /etc/mongodb.conf
  - sudo service mongodb restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15

script:
  - python setup.py test 
